MODEL:
  TYPE: vssm
  NAME: vssm1_tiny_0230
  DROP_PATH_RATE: 0.2
  VSSM:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 5, 2 ]
    SSM_D_STATE: 1
    SSM_DT_RANK: "auto"
    SSM_RATIO: 2.0
    SSM_CONV: 3
    SSM_CONV_BIAS: false
    MLP_RATIO: 4.0
    NORM_LAYER: "ln2d"
